#!/usr/bin/python3
# lists all states from the database hbtn_0e_0_usa
from 0-select_states import states
import MySQLdb
from sqlalchemy import create_engine, Session

engine = create_engine('mysql+mysqldb://mysql username:mysql password@localhost/database name', pool_pre_ping=True)

Base.metadata.create_all(engine)

session = Session(engine)
for state in session.query(State).order_by(State.id).all():
    print("{}: {}".format(state.id, state.name))
session.close()

#con = MySQLdb.connect(host = "localhost", user = "mysql username", passwd = "mysql password", database = "database name")
#sql = "SELECT * FROM states"
#for name in sql:
#    print(states.id, states.name)
